 package graphicaluserinterface;
/**
 *
 * @author keegan
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class StudentProgramme extends javax.swing.JFrame {
    /**
     * Creates new form StudentProgramme
     */
    Connection cn; //made cn global
    PreparedStatement pst;
    ResultSet rs;
    
    public StudentProgramme() { //constructor
        initComponents();
        getmyconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfirst = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlast = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfees = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        firstrecord = new javax.swing.JButton();
        lastrecord = new javax.swing.JButton();
        previousrecord = new javax.swing.JButton();
        nextrecord = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tableview = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        printrecords = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addrecord = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mclear = new javax.swing.JMenuItem();
        navigate = new javax.swing.JMenu();
        mfirstrecord = new javax.swing.JMenuItem();
        mlastrecord = new javax.swing.JMenuItem();
        mnextrecord = new javax.swing.JMenuItem();
        mpreviousrecord = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        mtableview = new javax.swing.JMenuItem();
        print = new javax.swing.JMenu();
        mprintrecord = new javax.swing.JMenuItem();
        close = new javax.swing.JMenu();
        mexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel1.setText("FirstName ");

        txtfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstActionPerformed(evt);
            }
        });

        jLabel2.setText("LastName");

        jLabel3.setText("Gender");

        jLabel4.setText("ID");

        jLabel5.setText("Fees");

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        firstrecord.setText("FirstRecord");
        firstrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstrecordActionPerformed(evt);
            }
        });

        lastrecord.setText("LastRecord");
        lastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastrecordActionPerformed(evt);
            }
        });

        previousrecord.setText("PreviousRecord");
        previousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousrecordActionPerformed(evt);
            }
        });

        nextrecord.setText("NextRecord");
        nextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextrecordActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Id Number", "Fees Payment"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        tableview.setText("TableView");
        tableview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableviewActionPerformed(evt);
            }
        });

        jLabel6.setText("Student Information");

        printrecords.setText("PrintRecords");
        printrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printrecordsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        addrecord.setText("AddRecord");
        addrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrecordActionPerformed(evt);
            }
        });
        jMenu1.add(addrecord);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mclear.setText("Clear");
        mclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mclearActionPerformed(evt);
            }
        });
        jMenu2.add(mclear);

        jMenuBar1.add(jMenu2);

        navigate.setText("Navigate");

        mfirstrecord.setText("FirstRecord");
        mfirstrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfirstrecordActionPerformed(evt);
            }
        });
        navigate.add(mfirstrecord);

        mlastrecord.setText("LastRecord");
        mlastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlastrecordActionPerformed(evt);
            }
        });
        navigate.add(mlastrecord);

        mnextrecord.setText("NextRecord");
        mnextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnextrecordActionPerformed(evt);
            }
        });
        navigate.add(mnextrecord);

        mpreviousrecord.setText("PreviousRecord");
        mpreviousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpreviousrecordActionPerformed(evt);
            }
        });
        navigate.add(mpreviousrecord);

        jMenuBar1.add(navigate);

        view.setText("View");

        mtableview.setText("TableView");
        mtableview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtableviewActionPerformed(evt);
            }
        });
        view.add(mtableview);

        jMenuBar1.add(view);

        print.setText("Print");

        mprintrecord.setText("PrintRecord");
        mprintrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprintrecordActionPerformed(evt);
            }
        });
        print.add(mprintrecord);

        jMenuBar1.add(print);

        close.setText("Close");

        mexit.setText("Exit");
        mexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mexitActionPerformed(evt);
            }
        });
        close.add(mexit);

        jMenuBar1.add(close);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(firstrecord)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastrecord))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nextrecord)
                                        .addGap(18, 18, 18)
                                        .addComponent(previousrecord)
                                        .addGap(18, 18, 18)
                                        .addComponent(tableview)
                                        .addGap(18, 18, 18)
                                        .addComponent(printrecords)))
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtlast)
                                            .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(submit)
                    .addComponent(firstrecord)
                    .addComponent(lastrecord))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousrecord)
                    .addComponent(nextrecord)
                    .addComponent(tableview)
                    .addComponent(printrecords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        getclear();
    }//GEN-LAST:event_clearActionPerformed

    private void txtfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        getrecords();
    }//GEN-LAST:event_submitActionPerformed

    private void firstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrecordActionPerformed
        // TODO add your handling code here:
        getfirstrecord();
    }//GEN-LAST:event_firstrecordActionPerformed

    private void lastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastrecordActionPerformed
        // TODO add your handling code here:
        getlastrecord();   
    }//GEN-LAST:event_lastrecordActionPerformed

    private void nextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextrecordActionPerformed
        // TODO add your handling code here:
        getnextrecord();
    }//GEN-LAST:event_nextrecordActionPerformed

    private void previousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousrecordActionPerformed
        // TODO add your handling code here:
        getpreviousrecord();
    }//GEN-LAST:event_previousrecordActionPerformed

    private void tableviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableviewActionPerformed
        // TODO add your handling code here:
        gettablerecords();
    }//GEN-LAST:event_tableviewActionPerformed

    private void printrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printrecordsActionPerformed
        // TODO add your handling code here:
        getprintrecords();
    }//GEN-LAST:event_printrecordsActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        getrecord();
    }//GEN-LAST:event_tableMouseClicked

    private void addrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrecordActionPerformed
        // TODO add your handling code here:
        getrecords();
    }//GEN-LAST:event_addrecordActionPerformed

    private void mclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mclearActionPerformed
        // TODO add your handling code here:
        getclear();
    }//GEN-LAST:event_mclearActionPerformed

    private void mfirstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfirstrecordActionPerformed
        // TODO add your handling code here:
        getfirstrecord();
    }//GEN-LAST:event_mfirstrecordActionPerformed

    private void mlastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlastrecordActionPerformed
        // TODO add your handling code here:
        getlastrecord();
    }//GEN-LAST:event_mlastrecordActionPerformed

    private void mnextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnextrecordActionPerformed
        // TODO add your handling code here:
        getnextrecord();
    }//GEN-LAST:event_mnextrecordActionPerformed

    private void mpreviousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpreviousrecordActionPerformed
        // TODO add your handling code here:
        getpreviousrecord();
    }//GEN-LAST:event_mpreviousrecordActionPerformed

    private void mtableviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtableviewActionPerformed
        // TODO add your handling code here:
        gettablerecords();
    }//GEN-LAST:event_mtableviewActionPerformed

    private void mprintrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprintrecordActionPerformed
        // TODO add your handling code here:
        getprintrecords();
    }//GEN-LAST:event_mprintrecordActionPerformed

    private void mexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexitActionPerformed
        // TODO add your handling code here:
        getexit();
    }//GEN-LAST:event_mexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProgramme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProgramme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProgramme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProgramme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create anfirstrecordy the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProgramme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addrecord;
    private javax.swing.JButton clear;
    private javax.swing.JMenu close;
    private javax.swing.JButton firstrecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastrecord;
    private javax.swing.JMenuItem mclear;
    private javax.swing.JMenuItem mexit;
    private javax.swing.JMenuItem mfirstrecord;
    private javax.swing.JMenuItem mlastrecord;
    private javax.swing.JMenuItem mnextrecord;
    private javax.swing.JMenuItem mpreviousrecord;
    private javax.swing.JMenuItem mprintrecord;
    private javax.swing.JMenuItem mtableview;
    private javax.swing.JMenu navigate;
    private javax.swing.JButton nextrecord;
    private javax.swing.JButton previousrecord;
    private javax.swing.JMenu print;
    private javax.swing.JButton printrecords;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    private javax.swing.JToggleButton tableview;
    private javax.swing.JTextField txtfees;
    private javax.swing.JTextField txtfirst;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlast;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables

    private void getmyconnection() {
        try
        {
            cn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb", "root", null);
            pst = cn.prepareStatement("Select * from studenttable", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.TYPE_FORWARD_ONLY);
            rs = pst.executeQuery();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getrecords() {
        try
        {
            pst = cn.prepareStatement("insert into studenttable values(?, ?, ?, ?, ?)");
            
            pst.setString(1, txtfirst.getText());
            pst.setString(2, txtlast.getText());
            pst.setString(3, txtgender.getText());
            pst.setString(4, txtid.getText());
            pst.setString(5, txtfees.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Record Successfully Added");
            getclear();
            new Demo().setVisible(true);
            dispose();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getclear() {
        txtfirst.setText(null);
        txtlast.setText(null);
        txtgender.setText(null);
        txtid.setText(null);
        txtfees.setText(null);
    }

    private void getfirstrecord() {
        try
        {
           rs.first();
           txtfirst.setText(rs.getString(1));
           txtlast.setText(rs.getString(2));
           txtgender.setText(rs.getString(3));
           txtid.setText(rs.getString(4));
           txtfees.setText(rs.getString(5));
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getlastrecord() {
        try
        {
           rs.last();
           txtfirst.setText(rs.getString(1));
           txtlast.setText(rs.getString(2));
           txtgender.setText(rs.getString(3));
           txtid.setText(rs.getString(4));
           txtfees.setText(rs.getString(5));
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getnextrecord() {
        try
        {
           if(rs.next() == true)
           {
           txtfirst.setText(rs.getString(1));
           txtlast.setText(rs.getString(2));
           txtgender.setText(rs.getString(3));
           txtid.setText(rs.getString(4));
           txtfees.setText(rs.getString(5));
           }
           else 
           rs.beforeFirst();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getpreviousrecord() {
        try
        {
           if(rs.previous() == true)
           {
           txtfirst.setText(rs.getString(1));
           txtlast.setText(rs.getString(2));
           txtgender.setText(rs.getString(3));
           txtid.setText(rs.getString(4));
           txtfees.setText(rs.getString(5));
           }
           else 
           rs.afterLast();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void gettablerecords() {
        try
        {
            getmyconnection();
            DefaultTableModel model = (DefaultTableModel) table.getModel(); // Generates Rows 
            model.setRowCount(0);
            while(rs.next()) // enables us to move from one row to the other
            {   
                String mydata [] = {rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3), 
                    rs.getString(4), 
                    rs.getString(5)}; // what data do we want
                
                        model.addRow(mydata);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }

    private void getprintrecords() {
        try 
        {
           gettablerecords();
           table.print();
        }
        catch(Exception e)
        {
            
            System.out.print(e);
        }
    }

    private void getrecord() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
       
            int row = table.getSelectedRow();
                
                txtfirst.setText(model.getValueAt(row, 0).toString());
                txtlast.setText(model.getValueAt(row, 1).toString());
                txtgender.setText(model.getValueAt(row, 2).toString());
                txtid.setText(model.getValueAt(row, 3).toString());
                txtfees.setText(model.getValueAt(row, 4).toString());
        }

    private void getexit() {
        System.exit(0);
    }
        
    }

